import type { CollegeCounselingData } from "./types";

export const collegeCounselingData: CollegeCounselingData = {
  activities_seed_rev: 3,
  profile: {
    full_name: "Emre Arslan",
    school: "TEV İnanç High School for the Gifted",
    country: "Türkiye",
    current_grade: "10th grade",
    graduation_year: 2028,
    citizenship: ["Turkish", "Bulgarian / EU"],
    intended_fields: ["Computer Science", "Applied AI", "Data Science"],
    positioning_idea:
      "Applied AI / Computer Vision / Data Science for high-stakes human systems: healthcare imaging, environmental/remote sensing, and online behavior.",
    us_strategy:
      "Full financial aid needed. US T20/reach-heavy applications should be balanced with Europe.",
    europe_strategy:
      "EU citizenship makes European universities financially attractive as a strong parallel plan.",
    academic_records: [
      { period: "Prep", gpa: 96.56 },
      { period: "Grade 9", gpa: 96.28 },
      { period: "Grade 10", gpa: 96.22, notes: "Current year (in progress)" },
    ],
    testing: [
      {
        name: "AP Statistics",
        status: "Taken",
        target: "Expected 5",
      },
      {
        name: "AP Computer Science A",
        status: "Taken",
        target: "Expected 5",
      },
      {
        name: "SAT (composite)",
        status: "Preparing",
        target: "1530–1560+",
      },
      {
        name: "SAT Math",
        status: "Preparing",
        target: "790–800",
      },
    ],
    constraints: [
      "Full financial aid required for US private colleges",
      "Prefer programs with research / applied AI pathways",
      "Balance US reach applications with Europe main plan",
    ],
    preferences: [
      "Strong CS / AI / Data Science curricula",
      "Research opportunities for undergrads",
      "International / English-taught options in Europe",
      "Communities that value building systems and leadership",
    ],
    positioning: {
      one_line:
        "Applied AI researcher-builder focused on computer vision and data science for high-stakes human systems.",
      common_app_bio:
        "I'm a student researcher and systems builder exploring how AI can support high-stakes human domains—from medical imaging to online behavior—while leading community infrastructure at my school.",
      research_heavy:
        "My work spans medical AI (lung CT segmentation), social computing/infodemiology with clinicians, and cross-modal vision research—always asking how models behave when decisions affect real people.",
      europe_technical:
        "EU-citizen CS/AI applicant with peer-reviewed research, industry/academia internships (Politecnico di Milano, Özyeğin), and a track record building production systems for school and community.",
    },
  },

  overview: {
    next_priority: "SAT foundation + CV cleanup + school list v1",
    applications_tracked: 28,
    essays_drafted: 0,
    financial_aid_status: "Planning / checklist started",
    counselor_readiness_score: 62,
    strategic_diagnosis:
      "US T20 is worth attempting but should not be the only plan; Europe should be a strong parallel plan because of EU citizenship and lower tuition.",
    current_positioning:
      "Applied AI / Computer Vision / Data Science for high-stakes human systems.",
    gpa_average: 96.35,
    sat_target: "1530–1560+",
  },

  activities: [
    {
      id: "act_polimi",
      title: "Politecnico di Milano - Department of Computer & Data Science",
      category: "Research",
      role: "Research Intern | Supervisor: Asst. Prof. Francesco Pierri",
      organization: "Politecnico di Milano",
      grade_levels: "2024.06-2024.08",
      hours_per_week: 20,
      weeks_per_year: 8,
      common_app_description:
        "Participated in a university-level computer and data science research environment, contributing to discussions on data-driven methodology and experimental design.",
      expanded_description: [
        "Summer internship",
        "Participated in a university-level computer and data science research environment, contributing to discussions on data-driven methodology and experimental design.",
        "Continued the research beyond the initial summer internship period, developing the work into an independent manuscript.",
      ].join("\n"),
      impact_metrics: "Internship completed; independent manuscript in progress",
      evidence_link: null,
      priority: "high",
      framing_notes: "Milan, Italy",
      risk_notes: "Keep description concrete on personal contribution",
      status: "ready",
    },
    {
      id: "act_pub",
      title: "Sole Author - Peer-Reviewed Publication",
      category: "Research / Publication",
      role: "Sole Author",
      organization: "Entertainment Computing (peer-reviewed)",
      grade_levels: "9–10",
      hours_per_week: 8,
      weeks_per_year: 40,
      common_app_description:
        "Authored a peer-reviewed research article analyzing 10,621 ranked League of Legends matches to examine how live streaming affects player performance and in-game behavior.",
      expanded_description: [
        "When the Audience Joins the Game: Live Streaming’s Influence on League of Legends Gameplay",
        "Authored a peer-reviewed research article analyzing 10,621 ranked League of Legends matches to examine how live streaming affects player performance and in-game behavior.",
        "Integrated large-scale gameplay data from the Riot Games API with Twitch streaming metadata, combining esports analytics, social computing, and quantitative performance analysis.",
        "Applied statistical comparisons and within-player analyses to evaluate behavioral adaptation and strategic decision-making under live audience observation.",
        "Publication: Arslan EA. When the audience joins the game: Live streaming’s influence on League of Legends gameplay. Entertainment Computing. 2026;57:101135. doi:10.1016/j.entcom.2026.101135.",
      ].join("\n"),
      impact_metrics:
        "1 peer-reviewed publication (Entertainment Computing 2026;57:101135)",
      evidence_link: "https://doi.org/10.1016/j.entcom.2026.101135",
      priority: "high",
      framing_notes: "Rare depth for grade level; pairs with social computing angle",
      risk_notes: "Avoid overselling; clarify methods and scope",
      status: "ready",
    },
    {
      id: "act_council",
      title: "Student Council President",
      category: "Leadership",
      role: "Student Council President (2025.09-2026.09); Student Council Vice President, previous term (2024.09-2025.09)",
      organization: "TEV İnanç Türkeş High School",
      grade_levels: "2024.09-2026.09",
      hours_per_week: 6,
      weeks_per_year: 36,
      common_app_description:
        "Elected to the student council in consecutive years, serving first as Vice President and currently as President.",
      expanded_description: [
        "Elected to the student council in consecutive years, serving first as Vice President and currently as President.",
        "Led institutional dialogue between students and administration, resulting in system-level policy changes improving academic life and student well-being.",
        "Played an active role in securing and presenting to potential donors, contributing to the school’s successful $1.8 million fundraising effort for campus development projects (dormitories, technology center, and social learning spaces). Designed and presented conceptual architectural and functional proposals for donor-facing development projects.",
        "Contributed to the school’s branding, vision, and mission development; collaborated on conceptual designs for the new school logo.",
        "Organized and led a student movement advocating for academic schedule reform; negotiated with administration to successfully optimize an efficient study session system, and eliminate Saturday study sessions.",
        "Oversaw student council budget allocation, managing ₺335,000 for student-focused programs, subscriptions, and institutional improvements.",
        "Co-developed and implemented “İnçnet,” a custom digital data and communication system, replacing a previously inefficient school-wide platform that the school administration used to pay for.",
      ].join("\n"),
      impact_metrics:
        "$1.8 million campus fundraising; ₺335,000 council budget; schedule reform; İnçnet",
      evidence_link: null,
      priority: "high",
      framing_notes: "Leadership without soft fluff; tie to systems thinking",
      risk_notes: "Quantify 1–2 concrete outcomes",
      status: "ready",
    },
    {
      id: "act_incnet",
      title: "İnçnet System",
      category: "Technology / Community",
      role: "Co-developer",
      organization: "TEV İnanç Türkeş High School",
      grade_levels: "9–10",
      hours_per_week: 5,
      weeks_per_year: 40,
      common_app_description:
        "Co-developed and implemented “İnçnet,” a custom digital data and communication system, replacing a previously inefficient school-wide platform that the school administration used to pay for.",
      expanded_description:
        "Co-developed and implemented “İnçnet,” a custom digital data and communication system, replacing a previously inefficient school-wide platform that the school administration used to pay for.",
      impact_metrics: "Replaced a paid school-wide platform with a custom system",
      evidence_link: null,
      priority: "high",
      framing_notes: "Builder identity; listed under Student Council on the CV",
      risk_notes: "Explain users and problem solved briefly",
      status: "ready",
    },
    {
      id: "act_entrepreneurship",
      title: "İnanç Entrepreneurship Club",
      category: "Entrepreneurship",
      role: "Club President (2025.04-2027.05); Club Member (2023.09-2025.04)",
      organization: "TEV İnanç Türkeş High School",
      grade_levels: "2023.09-2027.05",
      hours_per_week: 5,
      weeks_per_year: 36,
      common_app_description:
        "Led multidisciplinary teams to first place finishes in multiple ideathon competitions, developing solution oriented projects under time constraints.",
      expanded_description: [
        "Led multidisciplinary teams to first place finishes in multiple ideathon competitions, developing solution oriented projects under time constraints.",
        "Founded and organized a large-scale ideathon, featuring case studies from three companies, external sponsorship, and 150-200 participants.",
        "Coordinated logistics, sponsorship relations, case design, and evaluation processes.",
      ].join("\n"),
      impact_metrics: "First-place ideathons; 150–200 participant event",
      evidence_link: null,
      priority: "high",
      framing_notes: "Entrepreneurship & Innovation",
      risk_notes: "",
      status: "ready",
    },
    {
      id: "act_game",
      title: "Abyss Games Studio",
      category: "Entrepreneurship",
      role: "Club President (2025.04-2027.05); Club Member (2023.09-2025.04)",
      organization: "Abyss Games Studio",
      grade_levels: "2023.09-2027.05",
      hours_per_week: 5,
      weeks_per_year: 30,
      common_app_description:
        "Served as Project Manager, Game Designer, and Programmer for Midnight Entangled, an original indie game project.",
      expanded_description: [
        "Served as Project Manager, Game Designer, and Programmer for Midnight Entangled, an original indie game project.",
        "Selected by jury as one of Turkey’s Top 15 Video Games at MağaraJam’25, the country’s largest game jam event.",
        "Currently leading the active development of multiple original game projects within the club.",
      ].join("\n"),
      impact_metrics: "Turkey’s Top 15 Video Games at MağaraJam’25",
      evidence_link: null,
      priority: "medium",
      framing_notes: "Game Development & Creative Technology",
      risk_notes: "Don't crowd top 5",
      status: "ready",
    },
    {
      id: "act_frc",
      title: "Inanc Mechatronics Club",
      category: "STEM / Robotics",
      role: "Team Captain (2025.04-2026.05); Club Member (2023.09-2025.04)",
      organization: "FIRST Robotics Competition / TEV İnanç Türkeş High School",
      grade_levels: "2023.09-2026.05",
      hours_per_week: 12,
      weeks_per_year: 25,
      common_app_description:
        "Competed in FIRST Robotics Competition at Istanbul Regional 2024, Haliç Regional 2025, and Başkent Regional 2026. Went to the FRC Championship with the Impact Award in 2026.",
      expanded_description: [
        "Competed in FIRST Robotics Competition at Istanbul Regional 2024, Haliç Regional 2025, and Başkent Regional 2026. Went to the FRC Championship with the Impact Award in 2026.",
        "Led a FIRST awareness and educational resource initiative in collaboration with Khan Academy Türkiye:",
        "Developed publicly accessible FIRST robotics courses and videos to support beginner teams and students, published on first.partstopractice.org.",
        "Reached 52,200 people in total, including 25,000 viewers on YouTube and 27,200 users on the platform.",
        "Led international sustainability initiatives, including:",
        "Developed an electronic and mechanical guidance system using animal behavior-based directional sounds to help move wildlife away from forest fire danger zones, with support from IMC alumni at Virginia Tech and Dr. Yusuf Serkan Kılınç from Gazi University.",
        "Presented the project to schools, Codeavour participants, Gebze Forestry Directorate, and academic experts; published related educational materials through We Don’t Have Time, reaching 60,780 people in total.",
        "A Europe-wide sustainability documentary project supported by the Alstom Foundation, featuring collaborations with WWF, Greenpeace, Fridays for Future, and other global organizations.",
        "Led “FIRST Steps to Protect,” an environmental STEAM initiative developing a wildlife-guidance system for forest fires using animal behavior-based directional sounds, reaching 60,780 people through We Don’t Have Time, school presentations, Codeavour, Gebze Forestry Directorate, and educational materials.",
        "Led nationwide STEM outreach initiatives to address educational opportunity gaps:",
        "Visited 7 schools across Türkiye, reaching approximately 500 students (over half female).",
        "Introduced students to robotics, engineering principles, and FIRST programs through hands-on workshops and presentations.",
        "Directed “Hayal Kampı”, a social impact project supporting students affected by the 2023 earthquakes:",
        "Reached 850+ students through STEM and creative workshops.",
        "Co-created a children’s book based on students’ stories and illustrations, distributed directly to participants.",
        "Led international sustainability initiatives, including:",
        "Development and deployment of hydroponic systems near the Aral Sea region in collaboration with Yesenov University.",
        "A Europe-wide sustainability documentary project supported by the Alstom Foundation, featuring collaborations with WWF, Greenpeace, Fridays for Future, and other global organizations.",
        "Conducted international STEM outreach and robotics education programs in Bosnia and Herzegovina, delivering introductory robotics and programming curricula and supporting the formation of new competition teams.",
      ].join("\n"),
      impact_metrics:
        "FRC Championship + Impact Award 2026; 52,200 FIRST education reach; 60,780 sustainability reach; 850+ Hayal Kampı students",
      evidence_link: "https://first.partstopractice.org",
      priority: "high",
      framing_notes: "STEM Outreach & Social Impact",
      risk_notes: "Distinguish personal role from team achievements",
      status: "ready",
    },
    {
      id: "act_creanum",
      title: "Creanum",
      category: "Entrepreneurship / Service",
      role: "Co-Founder & President",
      organization: "Creanum",
      grade_levels: "2024.02-2027.05",
      hours_per_week: 4,
      weeks_per_year: 20,
      common_app_description:
        "Lead an independent, student-led fundraising initiative transforming artistic collaboration into social impact.",
      expanded_description: [
        "Lead an independent, student-led fundraising initiative transforming artistic collaboration into social impact.",
        "Raised ₺180,000+ through the sale of original student artworks to support the school’s Art Department.",
        "Represented the initiative at external events, including AmCham’s Chamber Corner,  IAmChampion Awarding Ceremony, and AWS Cloud Day and coordinated exhibitions and sales.",
      ].join("\n"),
      impact_metrics: "₺180,000+ raised for the Art Department",
      evidence_link: null,
      priority: "medium",
      framing_notes: "Arts, Fundraising & Social Entrepreneurship",
      risk_notes: "Add specific numbers when available",
      status: "ready",
    },
    {
      id: "act_lung",
      title: "Lung CT Segmentation / Medical AI Project",
      category: "Research",
      role: "Project Lead / Researcher",
      organization: "Independent / clinical collaborators",
      grade_levels: "10",
      hours_per_week: 10,
      weeks_per_year: 30,
      common_app_description:
        "Built lung CT segmentation pipeline exploring medical AI for high-stakes imaging decisions.",
      expanded_description:
        "Computer vision for healthcare imaging; dataset handling, model evaluation, clinical relevance.",
      impact_metrics: "Working pipeline; research narrative cornerstone",
      evidence_link: null,
      priority: "high",
      framing_notes: "Core positioning proof: high-stakes human systems",
      risk_notes: "Be careful with clinical claims; emphasize learning + rigor",
      status: "needs_revision",
    },
    {
      id: "act_ozyegin",
      title: "Özyeğin Cross-modal Vision AI Internship",
      category: "Research / Internship",
      role: "Intern",
      organization: "Özyeğin University",
      grade_levels: "10",
      hours_per_week: 15,
      weeks_per_year: 6,
      common_app_description:
        "Interned on cross-modal vision AI; experimented with multimodal representations.",
      expanded_description:
        "Remote sensing / vision-language style problems; mentorship in research workflow.",
      impact_metrics: "Internship completed; methods notebook / experiments",
      evidence_link: null,
      priority: "high",
      framing_notes: "Connects medical CV → multimodal / remote sensing arc",
      risk_notes: "Clarify deliverables",
      status: "draft",
    },
    {
      id: "act_info",
      title: "Infodemiology Studies with Dermatologists",
      category: "Research",
      role: "Student Researcher",
      organization: "Clinical collaborators",
      grade_levels: "9–10",
      hours_per_week: 6,
      weeks_per_year: 24,
      common_app_description:
        "Collaborated with dermatologists on infodemiology analyses of online health discourse.",
      expanded_description:
        "Social computing + public health lens; data ethics awareness with clinician partners.",
      impact_metrics: "Collaborative studies; clinician co-work",
      evidence_link: null,
      priority: "medium",
      framing_notes: "Online behavior + high-stakes human systems bridge",
      risk_notes: "Name specific methods lightly",
      status: "draft",
    },
  ],

  research: [
    {
      id: "res_lung",
      title: "Lung CT Segmentation for Medical Decision Support",
      field: "Medical AI / Computer Vision",
      mentor_institution: "Independent + clinical collaborators",
      dates: "2025–2026",
      methods: "Deep segmentation models, preprocessing, evaluation metrics",
      dataset_material: "CT imaging datasets (research use)",
      output: "Segmentation pipeline + analysis notes",
      publication_status: "In progress / exploratory",
      my_role: "End-to-end project ownership",
      what_this_proves:
        "Comfort with high-stakes domains, evaluation rigor, and CV for healthcare",
      next_step: "Strengthen baselines + write methods memo",
      link: null,
      category: "Medical AI / computer vision",
    },
    {
      id: "res_info",
      title: "Infodemiology with Dermatology Collaborators",
      field: "Social Computing / Public Health",
      mentor_institution: "Dermatologist collaborators",
      dates: "2024–2026",
      methods: "Online discourse analysis, descriptive stats, domain validation",
      dataset_material: "Public online health discussion signals",
      output: "Collaborative study drafts",
      publication_status: "Collaborative manuscripts / studies",
      my_role: "Student researcher + analyst",
      what_this_proves:
        "Cross-domain collaboration and sensitivity to online behavior → real outcomes",
      next_step: "Clarify contribution bullets for CV",
      link: null,
      category: "Social computing / infodemiology",
    },
    {
      id: "res_cross",
      title: "Cross-modal Vision AI (Özyeğin)",
      field: "Multimodal / Remote Sensing adjacent",
      mentor_institution: "Özyeğin University",
      dates: "2026",
      methods: "Cross-modal representations, experiment logging",
      dataset_material: "Vision / multimodal research datasets",
      output: "Internship experiments + notes",
      publication_status: "Internship output",
      my_role: "Intern",
      what_this_proves: "Breadth beyond single medical CV niche",
      next_step: "1-page summary of experiments for portfolio",
      link: null,
      category: "Remote sensing / cross-modal image generation",
    },
    {
      id: "res_esports",
      title: "Online Behavior / Esports Computational Study",
      field: "Entertainment Computing",
      mentor_institution: "Independent (sole author)",
      dates: "2024–2025",
      methods: "Computational analysis of online/esports behavior",
      dataset_material: "Domain-specific behavioral data",
      output: "Peer-reviewed sole-author paper",
      publication_status: "Published (Entertainment Computing)",
      my_role: "Sole author",
      what_this_proves: "Full research cycle ownership + publication maturity",
      next_step: "Cite cleanly; prepare 3-sentence lay summary",
      link: null,
      category: "Esports / online behavior",
    },
  ],

  research_narrative:
    "Across medical imaging, clinician-facing infodemiology, multimodal vision, and online behavior research, the through-line is the same: use data and models carefully where humans are at stake. Politecnico and Özyeğin experiences show I can work inside research environments; the sole-author paper shows I can finish the loop.",

  schools: [
    // US Need-Blind / Full-Need
    ...[
      ["MIT", "EECS / AI-related"],
      ["Princeton", "COS / related"],
      ["Harvard", "CS"],
      ["Yale", "CS"],
      ["Brown", "CS"],
      ["Dartmouth", "CS"],
      ["Amherst", "CS"],
      ["Bowdoin", "CS / Data"],
      ["Notre Dame", "CSE"],
      ["Washington & Lee", "CS"],
    ].map(([school, program], i) => ({
      id: `us_nb_${i}`,
      school_name: school,
      country: "USA",
      program,
      application_system: "Common App / school portal",
      deadline: "TBD (ED/EA/RD)",
      financial_aid_type: "Need-blind / full-need (verify annually)",
      financial_viability: "strong" as const,
      academic_fit: "high" as const,
      narrative_fit: "high" as const,
      reach_severity: (i < 6 ? "extreme" : "high") as "extreme" | "high",
      strategic_value: "high" as const,
      status: "researching" as const,
      notes: "Aid policy must be re-verified each cycle.",
      group: "us_need_blind" as const,
      requirements: ["Testing plan", "Essays", "Recommendations", "Aid forms"],
    })),

    // US Need-Aware
    ...[
      ["Stanford", "CS / AI"],
      ["Columbia", "CS"],
      ["Penn", "SEAS CS"],
      ["Duke", "CS"],
      ["UChicago", "CS"],
      ["Northwestern", "CS"],
      ["Vanderbilt", "CS"],
      ["Rice", "CS"],
      ["Williams", "CS"],
      ["Swarthmore", "CS"],
      ["Pomona", "CS"],
    ].map(([school, program], i) => ({
      id: `us_na_${i}`,
      school_name: school,
      country: "USA",
      program,
      application_system: "Common App / school portal",
      deadline: "TBD",
      financial_aid_type: "Need-aware (international)",
      financial_viability: "risky" as const,
      academic_fit: "high" as const,
      narrative_fit: "high" as const,
      reach_severity: "extreme" as const,
      strategic_value: (i < 4 ? "medium" : "low") as "medium" | "low",
      status: "researching" as const,
      notes: "Worth considering selectively; aid risk is real.",
      group: "us_need_aware" as const,
      requirements: ["Essays", "Recommendations", "Aid realism check"],
    })),

    // Europe main
    ...[
      ["TU Delft", "Netherlands", "CSE", "Studielink / TU Delft"],
      ["TU/e + Tilburg", "Netherlands", "Data Science", "Joint / portals"],
      ["Vrije Universiteit Amsterdam", "Netherlands", "AI / CS", "Studielink"],
      ["University of Groningen", "Netherlands", "AI", "Studielink"],
      ["Aalto University", "Finland", "Data Science / Computer Engineering", "Studyinfo"],
      ["Politecnico di Milano", "Italy", "English CS/AI-related programs", "PoliMi portal"],
    ].map(([school, country, program, system], i) => ({
      id: `eu_${i}`,
      school_name: school,
      country,
      program,
      application_system: system,
      deadline: "TBD (EU cycle)",
      financial_aid_type: "EU tuition / scholarships (citizenship advantage)",
      financial_viability: "strong" as const,
      academic_fit: "high" as const,
      narrative_fit: "high" as const,
      reach_severity: (i < 2 ? "high" : "moderate") as "high" | "moderate",
      strategic_value: "high" as const,
      status: "researching" as const,
      notes: "Core parallel plan; map English-taught tracks carefully.",
      group: "europe_main" as const,
      requirements: ["Transcripts", "Language/English proof if needed", "Motivation letter"],
    })),
  ],

  timeline: [
    {
      id: "t1",
      title: "SAT foundation",
      category: "Testing",
      period: "Summer 2026",
      deadline: "2026-08",
      priority: "high",
      status: "not_started",
      notes: "Math 790–800 focus; reading/writing plan",
    },
    {
      id: "t2",
      title: "Research continuation",
      category: "Research",
      period: "Summer 2026",
      deadline: "2026-08",
      priority: "high",
      status: "in_progress",
      notes: "Lung CT + portfolio write-ups",
    },
    {
      id: "t3",
      title: "CV cleanup",
      category: "Activities",
      period: "Summer 2026",
      deadline: "2026-07",
      priority: "high",
      status: "not_started",
      notes: "Common App 150-char drafts for top activities",
    },
    {
      id: "t4",
      title: "School list v1",
      category: "Strategy",
      period: "Summer 2026",
      deadline: "2026-08",
      priority: "high",
      status: "in_progress",
      notes: "US aid realism + Europe main plan",
    },
    {
      id: "t5",
      title: "SAT first attempt",
      category: "Testing",
      period: "Grade 11 Fall",
      deadline: "2026-12",
      priority: "high",
      status: "not_started",
      notes: "Target window TBD",
    },
    {
      id: "t6",
      title: "AP planning",
      category: "Academics",
      period: "Grade 11 Fall",
      deadline: "2026-10",
      priority: "medium",
      status: "not_started",
      notes: "Map remaining APs",
    },
    {
      id: "t7",
      title: "Essay idea bank",
      category: "Essays",
      period: "Grade 11 Fall",
      deadline: "2026-12",
      priority: "medium",
      status: "not_started",
      notes: "Collect stories; no forced drafts yet",
    },
    {
      id: "t8",
      title: "Recommendation teacher mapping",
      category: "Recommendations",
      period: "Grade 11 Spring",
      deadline: "2027-03",
      priority: "high",
      status: "not_started",
      notes: "STEM + humanities balance",
    },
    {
      id: "t9",
      title: "Summer program / internship applications",
      category: "Experiences",
      period: "Grade 11 Spring",
      deadline: "2027-04",
      priority: "medium",
      status: "not_started",
      notes: "Selective; quality over quantity",
    },
    {
      id: "t10",
      title: "Main essay drafts",
      category: "Essays",
      period: "Summer 2027",
      deadline: "2027-08",
      priority: "high",
      status: "not_started",
      notes: "Personal statement + why major",
    },
    {
      id: "t11",
      title: "Financial aid document preparation",
      category: "Financial Aid",
      period: "Summer 2027",
      deadline: "2027-09",
      priority: "high",
      status: "not_started",
      notes: "Status tracking only in Hub",
    },
    {
      id: "t12",
      title: "ED/EA submissions",
      category: "Applications",
      period: "Grade 12 Fall",
      deadline: "2027-11",
      priority: "high",
      status: "not_started",
      notes: "Only if strategy still favors early",
    },
    {
      id: "t13",
      title: "CSS Profile",
      category: "Financial Aid",
      period: "Grade 12 Fall",
      deadline: "2027-11",
      priority: "high",
      status: "not_started",
      notes: "School-specific deadlines vary",
    },
    {
      id: "t14",
      title: "Europe applications",
      category: "Applications",
      period: "Grade 12 Fall",
      deadline: "2028-01",
      priority: "high",
      status: "not_started",
      notes: "Parallel to US cycle",
    },
    {
      id: "t15",
      title: "Interviews",
      category: "Applications",
      period: "Grade 12 Fall",
      deadline: "2028-02",
      priority: "medium",
      status: "not_started",
      notes: "As offered",
    },
    {
      id: "t16",
      title: "Final decision",
      category: "Decision",
      period: "Grade 12 Spring",
      deadline: "2028-05",
      priority: "high",
      status: "not_started",
      notes: "Aid + fit comparison matrix",
    },
  ],

  essays: [
    {
      id: "e1",
      title: "AI research for high-stakes real-world problems",
      essay_type: "intellectual_curiosity",
      core_story:
        "How medical imaging / clinician collaboration taught me that models meet people at the decision boundary.",
      what_it_shows: "Intellectual depth, ethics awareness, research identity",
      risks: "Too technical; needs human moment",
      best_fit: "MIT, Princeton, TU Delft, PoliMi",
      status: "draft",
      draft_notes: "Start from a concrete experiment failure or surprise",
    },
    {
      id: "e2",
      title: "Understanding human behavior through data",
      essay_type: "personal_statement",
      core_story:
        "From esports/online behavior paper to infodemiology—curiosity about people in digital systems.",
      what_it_shows: "Interdisciplinary thinking",
      risks: "Could sound scattered without through-line",
      best_fit: "Brown, UChicago, VU Amsterdam AI",
      status: "draft",
      draft_notes: "Anchor on one vignette",
    },
    {
      id: "e3",
      title: "Building systems/community at TEV İnanç",
      essay_type: "leadership_community",
      core_story: "İnçnet + student council: shipping tools and representing people.",
      what_it_shows: "Builder-leader hybrid",
      risks: "List-y resume essay",
      best_fit: "Most US schools; Europe motivation letters",
      status: "draft",
      draft_notes: "One conflict → one system shipped",
    },
    {
      id: "e4",
      title: "FRC / İnçnet / Creanum as institution-building",
      essay_type: "leadership_community",
      core_story: "Creating durable infrastructure, not one-off events.",
      what_it_shows: "Ownership, community impact",
      risks: "Too many acronyms",
      best_fit: "Why school / activity essays",
      status: "draft",
      draft_notes: "Pick one primary thread",
    },
    {
      id: "e5",
      title: "Research as a thinking style",
      essay_type: "why_major",
      core_story: "Hypothesis → experiment → revision as identity, not CV decoration.",
      what_it_shows: "Fit for CS/AI majors",
      risks: "Abstract without scene",
      best_fit: "Why CS / Why AI supplements",
      status: "draft",
      draft_notes: "Pair with lung CT or publication anecdote",
    },
  ],

  financial_aid: {
    css_profile_required: true,
    noncustodial_form_required: false,
    noncustodial_waiver_needed: false,
    income_documents_collected: false,
    translations_needed: true,
    bank_statements_needed: false,
    school_specific_forms: true,
    submission_status: "Not started — planning phase",
    notes:
      "US full-need path requires careful school-by-school policy checks. Europe tuition advantage via EU citizenship is a core hedge.",
    next_actions: [
      "Verify need-blind/full-need lists for Class of 2028 cycle",
      "Create offline secure folder for real documents (not in Hub)",
      "List translation vendors if needed",
      "Map CSS Profile deadlines for shortlist",
    ],
  },

  recommendations: [
    {
      id: "rec1",
      name: "TBD — STEM teacher",
      subject_role: "Math / CS teacher",
      relationship_strength: "high",
      what_they_can_say: "Quantitative rigor, classroom leadership, project depth",
      evidence_to_send: "Research summary + activity metrics",
      brag_sheet_status: "not_started",
      deadline: "2027-09",
      request_status: "not_asked",
      thank_you_status: "pending",
      notes: "Map after Grade 11 course load clarifies",
    },
    {
      id: "rec2",
      name: "TBD — Humanities / counselor",
      subject_role: "English / counselor",
      relationship_strength: "medium",
      what_they_can_say: "Communication, character, community role",
      evidence_to_send: "Council + İnçnet narrative",
      brag_sheet_status: "not_started",
      deadline: "2027-09",
      request_status: "not_asked",
      thank_you_status: "pending",
      notes: "Build relationship intentionally in Grade 11",
    },
    {
      id: "rec3",
      name: "TBD — Research mentor",
      subject_role: "Research supervisor",
      relationship_strength: "high",
      what_they_can_say: "Independence, scientific maturity, collaboration",
      evidence_to_send: "Paper + project memo",
      brag_sheet_status: "not_started",
      deadline: "2027-10",
      request_status: "not_asked",
      thank_you_status: "pending",
      notes: "Optional third letter where allowed",
    },
  ],

  brag_sheet_notes:
    "Placeholder brag sheet: academics (GPA trend), testing targets, top 5 activities with metrics, research abstracts (3 sentences each), leadership outcomes, counselor talking points, and open questions.",

  weekly_checkins: [
    {
      id: "w1",
      week_date: "2026-07-14",
      what_i_did: "Outlined school list groups; drafted positioning one-liner",
      what_i_missed: "SAT timed section practice",
      biggest_progress: "Clearer US vs Europe strategy framing",
      biggest_concern: "Overweighting US T20 emotionally",
      new_achievement: "—",
      new_deadline: "School list v1 by end of summer",
      question_for_counselor:
        "How many need-aware US schools are worth the aid risk given EU options?",
      next_week_priorities: "CV 150-char drafts for top 5 activities; SAT math set",
      status: "shared",
    },
    {
      id: "w2",
      week_date: "2026-07-07",
      what_i_did: "Research portfolio outline; listed recommenders TBD",
      what_i_missed: "Essay vignette brainstorm",
      biggest_progress: "Connected medical AI ↔ online behavior narrative",
      biggest_concern: "Activity descriptions still too vague",
      new_achievement: "—",
      new_deadline: "—",
      question_for_counselor: "Which two activities should be demoted from top 10?",
      next_week_priorities: "Tighten Common App descriptions",
      status: "draft",
    },
  ],
};
